### ISSUE TITLE
Aggregate by family 

### ISSUE THREAD

**Issue by davelab6** [NeilSureshPatel/font-lang-support-afr#5]
Currently the web page reports raw per file data, it might be better to aggregates averages per family and then offer drill down for per file info

**Comment by davelab6** [comment]
Will this be in scope for current contract?

**Comment by NeilSureshPatel** [comment]
Yes, I am working on this right now. This update will be part of the current contract.

**Comment by NeilSureshPatel** [comment]
Feature added with [1fac030](https://github.com/JamraPatel/font-lang-support-afr/commit/1fac030b37f9f9313247d67322a41b84470f797a)
